INSERT INTO categories VALUES (1,'British Ale','https://res.cloudinary.com/deijy9qct/image/upload/v1632353983/BritishAle_ba2tan.jpg');
INSERT INTO categories VALUES (2,'Irish Ale','https://res.cloudinary.com/deijy9qct/image/upload/v1632353987/IrishAle_pw6ruw.jpg');
INSERT INTO categories VALUES (3,'North American Ale','https://res.cloudinary.com/deijy9qct/image/upload/v1632353980/AmericanAle_xjama4.jpg');
INSERT INTO categories VALUES (4,'German Ale','https://res.cloudinary.com/deijy9qct/image/upload/v1632353977/GermanAle_uepvpe.jpg');
INSERT INTO categories VALUES (5,'Belgian and French Ale','https://res.cloudinary.com/deijy9qct/image/upload/v1632353983/BelgianAndFrenchAle_v3l6hr.jpg');
INSERT INTO categories VALUES (6,'International Ale','https://res.cloudinary.com/deijy9qct/image/upload/v1632353988/InternationalBeer_dr3amg.jpg');
INSERT INTO categories VALUES (7,'German Lager','https://res.cloudinary.com/deijy9qct/image/upload/v1632353984/GermanLager_hrkkgw.jpg');
INSERT INTO categories VALUES (8,'North American Lager','https://res.cloudinary.com/deijy9qct/image/upload/v1632353988/NorthAmericanLager_xhv4pd.jpg');
INSERT INTO categories VALUES (9,'Other Lager','https://res.cloudinary.com/deijy9qct/image/upload/v1632353985/OtherLager_opasd4.jpg');
INSERT INTO categories VALUES (10,'International Lager','https://res.cloudinary.com/deijy9qct/image/upload/v1632353989/InternationalLager_davphz.jpg');
INSERT INTO categories VALUES (11,'Other Style','https://res.cloudinary.com/deijy9qct/image/upload/v1632353989/OtherStyle_zxxt6h.jpg');